# Numpy : efficient arrays and metrosism ?

In [1]:
import numpy as np

In [2]:
mylist = [1, 2, 3]
x = np.array(mylist)

In [3]:
x

array([1, 2, 3])

In [5]:
y = np.array([1,2,3,4,5])
y

array([1, 2, 3, 4, 5])

### 2D array (2*3)

In [45]:
m = np.array([[1, 2, 3], [10, 20, 30]])
m

array([[ 1,  2,  3],
       [10, 20, 30]])

In [46]:
print (m[0,0])
print (m[0,1])
print (m[0,2])
print (m[0])

1
2
3
[1 2 3]


In [47]:
print (m[:1])        # 2D slice of the big 2D aryay
print (m[:1][0])     # elem0 is a 1D array
print (m[:1][0][0])  # access to elem
print (m[:1][0][2])
print (m[1:2])
print (m[0:2][0:2][0:2][0:2][0:2][0:2][0:2]) # only first makes the change, same slice every time.


[[1 2 3]]
[1 2 3]
1
3
[[10 20 30]]
[[ 1  2  3]
 [10 20 30]]


In [48]:
m.shape

(2, 3)

### arrange() to create 1D array

In [50]:
n = np.arange(0, 30, 4) # 0..30 step 4
n

array([ 0,  4,  8, 12, 16, 20, 24, 28])

### linspace to create 1D array of fixed elements

In [73]:
n = np.linspace(0, 12, 3) # 1..12 . 4 items
n

array([  0.,   6.,  12.])

### reshape() to convert to 2D array

In [53]:
n = n.reshape(4,2)
n

array([[ 0,  4],
       [ 8, 12],
       [16, 20],
       [24, 28]])

In [54]:
n = n.reshape(2,4)
n

array([[ 0,  4,  8, 12],
       [16, 20, 24, 28]])

In [58]:
n = np.arange(0, 30, 5) # 0..30 step 4
n

array([ 0,  5, 10, 15, 20, 25])

In [72]:
n = np.linspace(0, 12, 3) # 1..12 . 4 items
n

array([  0.,   6.,  12.])

In [79]:
m = np.array([[1,2,3],[1,2,3], [1,2,4], [4,4,4]])

In [81]:
m.shape

(4, 3)

In [83]:
n=np.arange(0,30,2)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [91]:
d=np.linspace(10.0,100,4)
print (d)
print (d[0])
print (type(d[0]))


[  10.   40.   70.  100.]
10.0
<class 'numpy.float64'>


In [92]:
n=np.arange(0,30,2)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [105]:
n.reshape(3,5)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [110]:
n.reshape(5,3)

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [114]:
np.ones((5,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [115]:
np.zeros((2,2))

array([[ 0.,  0.],
       [ 0.,  0.]])

In [118]:
np.eye(6)

array([[ 1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.]])

In [122]:
np.diag([1,4,4,1])

array([[1, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 1]])

In [123]:
[1,2,3]*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [124]:
np.array([1,2,3]*3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [125]:
np.repeat([1,2,3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

## stacking np-arrays

In [128]:
p = np.ones([2,3], int)
p

array([[1, 1, 1],
       [1, 1, 1]])

In [131]:
np.vstack([p, 2*p, 3*p])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2],
       [3, 3, 3],
       [3, 3, 3]])

In [132]:
np.hstack([p, 2*p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

## Operations


In [134]:
x=np.array([1,2,3])
y=np.array([4,5,6])

In [138]:
print (x + y)
print (x * y)
print (x ** 2)

[5 7 9]
[ 4 10 18]
[1 4 9]


In [139]:
x.dot(y) # linear algebra (dot product)

32

In [140]:
z = np.array([y, y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

In [152]:
z.shape


(2, 3)

In [153]:
z.T.shape ### transposing

(3, 2)

In [154]:
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [155]:
z.dtype

dtype('int64')

In [158]:
#z = z.astype('float64')
z = z.astype('f')
z.dtype

dtype('float32')

## Math functions

In [159]:
a = np.array([-4,-2,1,3,5])

In [165]:
print (a.sum())
print (a.max())
print (a.min())
print (a.mean())
print (a.std())
print (a.argmax())
print (a.argmin())


3
5
-4
0.6
3.26190128606
4
0


## Indexing / Slicing

In [170]:
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [175]:
s[0], s[5], s[5:6], s[4:7] # note that s5:6 is array of 1 elem

(0, 25, array([25]), array([16, 25, 36]))

In [179]:
s = np.arange(10)
s

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [220]:
print (s[-5:-1])
print (s[-5::-4])

[5 6 7 8]
[5 1]


## 2d array

In [215]:
r = np.arange(36)
r.resize((6,6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [216]:
r[2,2]

14

In [217]:
r[3,3:10] # slice can overflow

array([21, 22, 23])

In [259]:
r[1:8:2, 1:8:2] # indexing 1..8 step2 (2,4,6)

array([[ 7,  9, 11],
       [19, 21, 23],
       [31, 33, 35]])

In [261]:
r[r>3]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35])

In [263]:
r[r>30]=30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [265]:
r2 = r[:3,:3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

## slicing returns the same array ref

In [267]:
r2[:] =0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [268]:
r


array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [269]:
r_copy = r.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [272]:
r_copy[:3,:3] = 99
r_copy

array([[99, 99, 99,  3,  4,  5],
       [99, 99, 99,  9, 10, 11],
       [99, 99, 99, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [273]:
old = np.array([[1, 1, 1],
                [1, 1, 1]])

new = old
new[0, :2] = 0

print(old)

[[0 0 1]
 [1 1 1]]


In [ ]:
old = np.array([[1, 1, 1],
                [1, 1, 1]])

new = old.copy()
new[:, 0] = 0

print(old)


## Iterating over numpyArray

In [278]:
test = np.random.randint(0,10, (4,3))
test

array([[3, 2, 1],
       [0, 5, 4],
       [6, 0, 1],
       [0, 6, 8]])

In [284]:
for row in test:
    print (row)
    

[3 2 1]
[0 5 4]
[6 0 1]
[0 6 8]


In [287]:
for i in range(len(test)):
    print (test[i])



[3 2 1]
[0 5 4]
[6 0 1]
[0 6 8]


In [288]:
test2 = test**2
print (test)
print (test2)

[[3 2 1]
 [0 5 4]
 [6 0 1]
 [0 6 8]]
[[ 9  4  1]
 [ 0 25 16]
 [36  0  1]
 [ 0 36 64]]


In [290]:
for i,j in zip(test, test2):
    print ('{} + {} = {}'.format(i, j, i+j))

[3 2 1] + [9 4 1] = [12  6  2]
[0 5 4] + [ 0 25 16] = [ 0 30 20]
[6 0 1] + [36  0  1] = [42  0  2]
[0 6 8] + [ 0 36 64] = [ 0 42 72]
